./bin/metamap16 -q /gpfs_home/vsharma6/data/vsharma6/palau_ascii/Adiantum_philippense_ascii.txt /gpfs_home/vsharma6/data/vsharma6/palau_out/Adiantum_philippense_out.txt
./bin/metamap16 -q /gpfs_home/vsharma6/data/vsharma6/palau_ascii/Ageratum_conyzoides_ascii.txt /gpfs_home/vsharma6/data/vsharma6/palau_out/Ageratum_conyzoides_out.txt
./bin/metamap16 -q /gpfs_home/vsharma6/data/vsharma6/palau_ascii/Aidia_racemosa_ascii.txt /gpfs_home/vsharma6/data/vsharma6/palau_out/Aidia_racemosa_out.txt
./bin/metamap16 -q /gpfs_home/vsharma6/data/vsharma6/palau_ascii/Allium_cepa_ascii.txt /gpfs_home/vsharma6/data/vsharma6/palau_out/Allium_cepa_out.txt
./bin/metamap16 -q /gpfs_home/vsharma6/data/vsharma6/palau_ascii/Allophylus_timoriensis_ascii.txt /gpfs_home/vsharma6/data/vsharma6/palau_out/Allophylus_timoriensis_out.txt
./bin/metamap16 -q /gpfs_home/vsharma6/data/vsharma6/palau_ascii/Angiopteris_evecta_ascii.txt /gpfs_home/vsharma6/data/vsharma6/palau_out/Angiopteris_evecta_out.txt
./bin/metamap16 -q /gpfs_home/vsharma6/data/vsharma6/palau_ascii/Annona_muricata_ascii.txt /gpfs_home/vsharma6/data/vsharma6/palau_out/Annona_muricata_out.txt
./bin/metamap16 -q /gpfs_home/vsharma6/data/vsharma6/palau_ascii/Artocarpus_atilis_ascii.txt /gpfs_home/vsharma6/data/vsharma6/palau_out/Artocarpus_atilis_out.txt
./bin/metamap16 -q /gpfs_home/vsharma6/data/vsharma6/palau_ascii/Atuna_racemosa_ascii.txt /gpfs_home/vsharma6/data/vsharma6/palau_out/Atuna_racemosa_out.txt
./bin/metamap16 -q /gpfs_home/vsharma6/data/vsharma6/palau_ascii/Averrhoa_bilimbi_ascii.txt /gpfs_home/vsharma6/data/vsharma6/palau_out/Averrhoa_bilimbi_out.txt
./bin/metamap16 -q /gpfs_home/vsharma6/data/vsharma6/palau_ascii/Barringtonia_racemosa_ascii.txt /gpfs_home/vsharma6/data/vsharma6/palau_out/Barringtonia_racemosa_out.txt
./bin/metamap16 -q /gpfs_home/vsharma6/data/vsharma6/palau_ascii/Callicarpa_elegans_ascii.txt /gpfs_home/vsharma6/data/vsharma6/palau_out/Callicarpa_elegans_out.txt
./bin/metamap16 -q /gpfs_home/vsharma6/data/vsharma6/palau_ascii/Calophyllum_inophyllum_ascii.txt /gpfs_home/vsharma6/data/vsharma6/palau_out/Calophyllum_inophyllum_out.txt
./bin/metamap16 -q /gpfs_home/vsharma6/data/vsharma6/palau_ascii/Casearia_hietella_ascii.txt /gpfs_home/vsharma6/data/vsharma6/palau_out/Casearia_hietella_out.txt
./bin/metamap16 -q /gpfs_home/vsharma6/data/vsharma6/palau_ascii/Cerbera_manghas_ascii.txt /gpfs_home/vsharma6/data/vsharma6/palau_out/Cerbera_manghas_out.txt
./bin/metamap16 -q /gpfs_home/vsharma6/data/vsharma6/palau_ascii/Cheilocostus_speciosus_ascii.txt /gpfs_home/vsharma6/data/vsharma6/palau_out/Cheilocostus_speciosus_out.txt
./bin/metamap16 -q /gpfs_home/vsharma6/data/vsharma6/palau_ascii/Chromolaena_odorata_ascii.txt /gpfs_home/vsharma6/data/vsharma6/palau_out/Chromolaena_odorata_out.txt
./bin/metamap16 -q /gpfs_home/vsharma6/data/vsharma6/palau_ascii/Citrus_aurantiifolia_ascii.txt /gpfs_home/vsharma6/data/vsharma6/palau_out/Citrus_aurantiifolia_out.txt
./bin/metamap16 -q /gpfs_home/vsharma6/data/vsharma6/palau_ascii/Citrus_mitis_ascii.txt /gpfs_home/vsharma6/data/vsharma6/palau_out/Citrus_mitis_out.txt
./bin/metamap16 -q /gpfs_home/vsharma6/data/vsharma6/palau_ascii/Citrus_spp_ascii.txt /gpfs_home/vsharma6/data/vsharma6/palau_out/Citrus_spp_out.txt
./bin/metamap16 -q /gpfs_home/vsharma6/data/vsharma6/palau_ascii/Clerodendrum_paniculatum_ascii.txt /gpfs_home/vsharma6/data/vsharma6/palau_out/Clerodendrum_paniculatum_out.txt
./bin/metamap16 -q /gpfs_home/vsharma6/data/vsharma6/palau_ascii/Cocos_nucifera_ascii.txt /gpfs_home/vsharma6/data/vsharma6/palau_out/Cocos_nucifera_out.txt
./bin/metamap16 -q /gpfs_home/vsharma6/data/vsharma6/palau_ascii/Codiaeum_variegatum_ascii.txt /gpfs_home/vsharma6/data/vsharma6/palau_out/Codiaeum_variegatum_out.txt
./bin/metamap16 -q /gpfs_home/vsharma6/data/vsharma6/palau_ascii/Colocasia_esculenta_ascii.txt /gpfs_home/vsharma6/data/vsharma6/palau_out/Colocasia_esculenta_out.txt
./bin/metamap16 -q /gpfs_home/vsharma6/data/vsharma6/palau_ascii/Cordyline_fruticosa_ascii.txt /gpfs_home/vsharma6/data/vsharma6/palau_out/Cordyline_fruticosa_out.txt
./bin/metamap16 -q /gpfs_home/vsharma6/data/vsharma6/palau_ascii/Curcuma_longa_ascii.txt /gpfs_home/vsharma6/data/vsharma6/palau_out/Curcuma_longa_out.txt
./bin/metamap16 -q /gpfs_home/vsharma6/data/vsharma6/palau_ascii/Derris_trifoliata_ascii.txt /gpfs_home/vsharma6/data/vsharma6/palau_out/Derris_trifoliata_out.txt
./bin/metamap16 -q /gpfs_home/vsharma6/data/vsharma6/palau_ascii/Dianella_carolinensis_ascii.txt /gpfs_home/vsharma6/data/vsharma6/palau_out/Dianella_carolinensis_out.txt
./bin/metamap16 -q /gpfs_home/vsharma6/data/vsharma6/palau_ascii/Dolichandrone_spathacea_ascii.txt /gpfs_home/vsharma6/data/vsharma6/palau_out/Dolichandrone_spathacea_out.txt
./bin/metamap16 -q /gpfs_home/vsharma6/data/vsharma6/palau_ascii/Epipremnum_pinnatum_ascii.txt /gpfs_home/vsharma6/data/vsharma6/palau_out/Epipremnum_pinnatum_out.txt
./bin/metamap16 -q /gpfs_home/vsharma6/data/vsharma6/palau_ascii/Flacourtia_rukam_ascii.txt /gpfs_home/vsharma6/data/vsharma6/palau_out/Flacourtia_rukam_out.txt
./bin/metamap16 -q /gpfs_home/vsharma6/data/vsharma6/palau_ascii/Flemingia_strobilifera_ascii.txt /gpfs_home/vsharma6/data/vsharma6/palau_out/Flemingia_strobilifera_out.txt
./bin/metamap16 -q /gpfs_home/vsharma6/data/vsharma6/palau_ascii/Glochidion_ramiflorum_ascii.txt /gpfs_home/vsharma6/data/vsharma6/palau_out/Glochidion_ramiflorum_out.txt
./bin/metamap16 -q /gpfs_home/vsharma6/data/vsharma6/palau_ascii/Heritiera_littoralis_ascii.txt /gpfs_home/vsharma6/data/vsharma6/palau_out/Heritiera_littoralis_out.txt
./bin/metamap16 -q /gpfs_home/vsharma6/data/vsharma6/palau_ascii/Hibiscus_rosa-sinensis_ascii.txt /gpfs_home/vsharma6/data/vsharma6/palau_out/Hibiscus_rosa-sinensis_out.txt
./bin/metamap16 -q /gpfs_home/vsharma6/data/vsharma6/palau_ascii/Horsfieldia_irya_ascii.txt /gpfs_home/vsharma6/data/vsharma6/palau_out/Horsfieldia_irya_out.txt
./bin/metamap16 -q /gpfs_home/vsharma6/data/vsharma6/palau_ascii/Ixora_casei_ascii.txt /gpfs_home/vsharma6/data/vsharma6/palau_out/Ixora_casei_out.txt
./bin/metamap16 -q /gpfs_home/vsharma6/data/vsharma6/palau_ascii/Lycopodiella_cernua_ascii.txt /gpfs_home/vsharma6/data/vsharma6/palau_out/Lycopodiella_cernua_out.txt
./bin/metamap16 -q /gpfs_home/vsharma6/data/vsharma6/palau_ascii/Macaranga_carolinensis_ascii.txt /gpfs_home/vsharma6/data/vsharma6/palau_out/Macaranga_carolinensis_out.txt
./bin/metamap16 -q /gpfs_home/vsharma6/data/vsharma6/palau_ascii/Melicope_denhamii_ascii.txt /gpfs_home/vsharma6/data/vsharma6/palau_out/Melicope_denhamii_out.txt
./bin/metamap16 -q /gpfs_home/vsharma6/data/vsharma6/palau_ascii/Microsorum_scolopendria_ascii.txt /gpfs_home/vsharma6/data/vsharma6/palau_out/Microsorum_scolopendria_out.txt
./bin/metamap16 -q /gpfs_home/vsharma6/data/vsharma6/palau_ascii/Musa_paradisiaca_ascii.txt /gpfs_home/vsharma6/data/vsharma6/palau_out/Musa_paradisiaca_out.txt
./bin/metamap16 -q /gpfs_home/vsharma6/data/vsharma6/palau_ascii/Nepenthes_mirabilis_ascii.txt /gpfs_home/vsharma6/data/vsharma6/palau_out/Nepenthes_mirabilis_out.txt
./bin/metamap16 -q /gpfs_home/vsharma6/data/vsharma6/palau_ascii/Nephrolepis_acutifolia_ascii.txt /gpfs_home/vsharma6/data/vsharma6/palau_out/Nephrolepis_acutifolia_out.txt
./bin/metamap16 -q /gpfs_home/vsharma6/data/vsharma6/palau_ascii/Pangium_edule_ascii.txt /gpfs_home/vsharma6/data/vsharma6/palau_out/Pangium_edule_out.txt
./bin/metamap16 -q /gpfs_home/vsharma6/data/vsharma6/palau_ascii/Paraderris_elliptica_ascii.txt /gpfs_home/vsharma6/data/vsharma6/palau_out/Paraderris_elliptica_out.txt
./bin/metamap16 -q /gpfs_home/vsharma6/data/vsharma6/palau_ascii/Pemphis_acidula_ascii.txt /gpfs_home/vsharma6/data/vsharma6/palau_out/Pemphis_acidula_out.txt
./bin/metamap16 -q /gpfs_home/vsharma6/data/vsharma6/palau_ascii/Peperomia_pellucida_ascii.txt /gpfs_home/vsharma6/data/vsharma6/palau_out/Peperomia_pellucida_out.txt
./bin/metamap16 -q /gpfs_home/vsharma6/data/vsharma6/palau_ascii/Persea_americana_ascii.txt /gpfs_home/vsharma6/data/vsharma6/palau_out/Persea_americana_out.txt
./bin/metamap16 -q /gpfs_home/vsharma6/data/vsharma6/palau_ascii/Phaleria_nisidai_ascii.txt /gpfs_home/vsharma6/data/vsharma6/palau_out/Phaleria_nisidai_out.txt
./bin/metamap16 -q /gpfs_home/vsharma6/data/vsharma6/palau_ascii/Phyllanthus_palauensis_ascii.txt /gpfs_home/vsharma6/data/vsharma6/palau_out/Phyllanthus_palauensis_out.txt
./bin/metamap16 -q /gpfs_home/vsharma6/data/vsharma6/palau_ascii/Piper_betle_ascii.txt /gpfs_home/vsharma6/data/vsharma6/palau_out/Piper_betle_out.txt
./bin/metamap16 -q /gpfs_home/vsharma6/data/vsharma6/palau_ascii/Piriqueta_racemosa_ascii.txt /gpfs_home/vsharma6/data/vsharma6/palau_out/Piriqueta_racemosa_out.txt
./bin/metamap16 -q /gpfs_home/vsharma6/data/vsharma6/palau_ascii/Pouteria_obovata_ascii.txt /gpfs_home/vsharma6/data/vsharma6/palau_out/Pouteria_obovata_out.txt
./bin/metamap16 -q /gpfs_home/vsharma6/data/vsharma6/palau_ascii/Premna_serratifolia_ascii.txt /gpfs_home/vsharma6/data/vsharma6/palau_out/Premna_serratifolia_out.txt
./bin/metamap16 -q /gpfs_home/vsharma6/data/vsharma6/palau_ascii/Psidium_guajava_ascii.txt /gpfs_home/vsharma6/data/vsharma6/palau_out/Psidium_guajava_out.txt
./bin/metamap16 -q /gpfs_home/vsharma6/data/vsharma6/palau_ascii/Rhus_taitensis_ascii.txt /gpfs_home/vsharma6/data/vsharma6/palau_out/Rhus_taitensis_out.txt
./bin/metamap16 -q /gpfs_home/vsharma6/data/vsharma6/palau_ascii/Scaevola_taccada_ascii.txt /gpfs_home/vsharma6/data/vsharma6/palau_out/Scaevola_taccada_out.txt
./bin/metamap16 -q /gpfs_home/vsharma6/data/vsharma6/palau_ascii/Scyphiphora_hydrophyllacea_ascii.txt /gpfs_home/vsharma6/data/vsharma6/palau_out/Scyphiphora_hydrophyllacea_out.txt
./bin/metamap16 -q /gpfs_home/vsharma6/data/vsharma6/palau_ascii/Semecarpus_venenosus_ascii.txt /gpfs_home/vsharma6/data/vsharma6/palau_out/Semecarpus_venenosus_out.txt
./bin/metamap16 -q /gpfs_home/vsharma6/data/vsharma6/palau_ascii/Senna_obtusifolia_ascii.txt /gpfs_home/vsharma6/data/vsharma6/palau_out/Senna_obtusifolia_out.txt
./bin/metamap16 -q /gpfs_home/vsharma6/data/vsharma6/palau_ascii/Syzygium_samarangense_ascii.txt /gpfs_home/vsharma6/data/vsharma6/palau_out/Syzygium_samarangense_out.txt
./bin/metamap16 -q /gpfs_home/vsharma6/data/vsharma6/palau_ascii/Terminalia_catappa_ascii.txt /gpfs_home/vsharma6/data/vsharma6/palau_out/Terminalia_catappa_out.txt
./bin/metamap16 -q /gpfs_home/vsharma6/data/vsharma6/palau_ascii/Terminalia_crassipes_ascii.txt /gpfs_home/vsharma6/data/vsharma6/palau_out/Terminalia_crassipes_out.txt
./bin/metamap16 -q /gpfs_home/vsharma6/data/vsharma6/palau_ascii/Vitex_trifolia_ascii.txt /gpfs_home/vsharma6/data/vsharma6/palau_out/Vitex_trifolia_out.txt
