./bin/metamap16 -q /gpfs_home/vsharma6/data/vsharma6/pohnpei_ascii/Allophylus_timoriensis_ascii.txt /gpfs_home/vsharma6/data/vsharma6/pohnpei_out/Allophylus_timoriensis_out.txt
./bin/metamap16 -q /gpfs_home/vsharma6/data/vsharma6/pohnpei_ascii/Alocasia_macrorrhizos_ascii.txt /gpfs_home/vsharma6/data/vsharma6/pohnpei_out/Alocasia_macrorrhizos_out.txt
./bin/metamap16 -q /gpfs_home/vsharma6/data/vsharma6/pohnpei_ascii/Annona_muricata_ascii.txt /gpfs_home/vsharma6/data/vsharma6/pohnpei_out/Annona_muricata_out.txt
./bin/metamap16 -q /gpfs_home/vsharma6/data/vsharma6/pohnpei_ascii/Areca_catechu_ascii.txt /gpfs_home/vsharma6/data/vsharma6/pohnpei_out/Areca_catechu_out.txt
./bin/metamap16 -q /gpfs_home/vsharma6/data/vsharma6/pohnpei_ascii/Artocarpus_altilis_ascii.txt /gpfs_home/vsharma6/data/vsharma6/pohnpei_out/Artocarpus_altilis_out.txt
./bin/metamap16 -q /gpfs_home/vsharma6/data/vsharma6/pohnpei_ascii/Barringtonia_racemosa_ascii.txt /gpfs_home/vsharma6/data/vsharma6/pohnpei_out/Barringtonia_racemosa_out.txt
./bin/metamap16 -q /gpfs_home/vsharma6/data/vsharma6/pohnpei_ascii/Blyxa_aubertii_ascii.txt /gpfs_home/vsharma6/data/vsharma6/pohnpei_out/Blyxa_aubertii_out.txt
./bin/metamap16 -q /gpfs_home/vsharma6/data/vsharma6/pohnpei_ascii/Bruguiera_gymnorrhiza_ascii.txt /gpfs_home/vsharma6/data/vsharma6/pohnpei_out/Bruguiera_gymnorrhiza_out.txt
./bin/metamap16 -q /gpfs_home/vsharma6/data/vsharma6/pohnpei_ascii/Campnosperma_brevipetiolata_ascii.txt /gpfs_home/vsharma6/data/vsharma6/pohnpei_out/Campnosperma_brevipetiolata_out.txt
./bin/metamap16 -q /gpfs_home/vsharma6/data/vsharma6/pohnpei_ascii/Carica_papaya_ascii.txt /gpfs_home/vsharma6/data/vsharma6/pohnpei_out/Carica_papaya_out.txt
./bin/metamap16 -q /gpfs_home/vsharma6/data/vsharma6/pohnpei_ascii/Ceiba_pentandra_ascii.txt /gpfs_home/vsharma6/data/vsharma6/pohnpei_out/Ceiba_pentandra_out.txt
./bin/metamap16 -q /gpfs_home/vsharma6/data/vsharma6/pohnpei_ascii/Centella_asiatica_ascii.txt /gpfs_home/vsharma6/data/vsharma6/pohnpei_out/Centella_asiatica_out.txt
./bin/metamap16 -q /gpfs_home/vsharma6/data/vsharma6/pohnpei_ascii/Cinnamomum_carolinense_ascii.txt /gpfs_home/vsharma6/data/vsharma6/pohnpei_out/Cinnamomum_carolinense_out.txt
./bin/metamap16 -q /gpfs_home/vsharma6/data/vsharma6/pohnpei_ascii/Citrus_aurantifolia_ascii.txt /gpfs_home/vsharma6/data/vsharma6/pohnpei_out/Citrus_aurantifolia_out.txt
./bin/metamap16 -q /gpfs_home/vsharma6/data/vsharma6/pohnpei_ascii/Citrus_limon_ascii.txt /gpfs_home/vsharma6/data/vsharma6/pohnpei_out/Citrus_limon_out.txt
./bin/metamap16 -q /gpfs_home/vsharma6/data/vsharma6/pohnpei_ascii/Claoxylon_carolinianum_ascii.txt /gpfs_home/vsharma6/data/vsharma6/pohnpei_out/Claoxylon_carolinianum_out.txt
./bin/metamap16 -q /gpfs_home/vsharma6/data/vsharma6/pohnpei_ascii/Clerodendrum_inerme_ascii.txt /gpfs_home/vsharma6/data/vsharma6/pohnpei_out/Clerodendrum_inerme_out.txt
./bin/metamap16 -q /gpfs_home/vsharma6/data/vsharma6/pohnpei_ascii/Cocos_nucifera_ascii.txt /gpfs_home/vsharma6/data/vsharma6/pohnpei_out/Cocos_nucifera_out.txt
./bin/metamap16 -q /gpfs_home/vsharma6/data/vsharma6/pohnpei_ascii/Colocasia_esculenta_ascii.txt /gpfs_home/vsharma6/data/vsharma6/pohnpei_out/Colocasia_esculenta_out.txt
./bin/metamap16 -q /gpfs_home/vsharma6/data/vsharma6/pohnpei_ascii/Cordyline_fruticosa_ascii.txt /gpfs_home/vsharma6/data/vsharma6/pohnpei_out/Cordyline_fruticosa_out.txt
./bin/metamap16 -q /gpfs_home/vsharma6/data/vsharma6/pohnpei_ascii/Curcuma_longa_ascii.txt /gpfs_home/vsharma6/data/vsharma6/pohnpei_out/Curcuma_longa_out.txt
./bin/metamap16 -q /gpfs_home/vsharma6/data/vsharma6/pohnpei_ascii/Cyathula_prostrata_ascii.txt /gpfs_home/vsharma6/data/vsharma6/pohnpei_out/Cyathula_prostrata_out.txt
./bin/metamap16 -q /gpfs_home/vsharma6/data/vsharma6/pohnpei_ascii/Cyclosorus_heterocarpus_ascii.txt /gpfs_home/vsharma6/data/vsharma6/pohnpei_out/Cyclosorus_heterocarpus_out.txt
./bin/metamap16 -q /gpfs_home/vsharma6/data/vsharma6/pohnpei_ascii/Cyclosorus_maenomensis_ascii.txt /gpfs_home/vsharma6/data/vsharma6/pohnpei_out/Cyclosorus_maenomensis_out.txt
./bin/metamap16 -q /gpfs_home/vsharma6/data/vsharma6/pohnpei_ascii/Davallia_solida_ascii.txt /gpfs_home/vsharma6/data/vsharma6/pohnpei_out/Davallia_solida_out.txt
./bin/metamap16 -q /gpfs_home/vsharma6/data/vsharma6/pohnpei_ascii/Dioscorea_bulbifera_ascii.txt /gpfs_home/vsharma6/data/vsharma6/pohnpei_out/Dioscorea_bulbifera_out.txt
./bin/metamap16 -q /gpfs_home/vsharma6/data/vsharma6/pohnpei_ascii/Erythrina_fusca_ascii.txt /gpfs_home/vsharma6/data/vsharma6/pohnpei_out/Erythrina_fusca_out.txt
./bin/metamap16 -q /gpfs_home/vsharma6/data/vsharma6/pohnpei_ascii/Fagraea_berteroana_ascii.txt /gpfs_home/vsharma6/data/vsharma6/pohnpei_out/Fagraea_berteroana_out.txt
./bin/metamap16 -q /gpfs_home/vsharma6/data/vsharma6/pohnpei_ascii/Fibloboletus_manipularis_ascii.txt /gpfs_home/vsharma6/data/vsharma6/pohnpei_out/Fibloboletus_manipularis_out.txt
./bin/metamap16 -q /gpfs_home/vsharma6/data/vsharma6/pohnpei_ascii/Ficus_prolixa_ascii.txt /gpfs_home/vsharma6/data/vsharma6/pohnpei_out/Ficus_prolixa_out.txt
./bin/metamap16 -q /gpfs_home/vsharma6/data/vsharma6/pohnpei_ascii/Ficus_tinctoria_ascii.txt /gpfs_home/vsharma6/data/vsharma6/pohnpei_out/Ficus_tinctoria_out.txt
./bin/metamap16 -q /gpfs_home/vsharma6/data/vsharma6/pohnpei_ascii/Glochidion_marianum_ascii.txt /gpfs_home/vsharma6/data/vsharma6/pohnpei_out/Glochidion_marianum_out.txt
./bin/metamap16 -q /gpfs_home/vsharma6/data/vsharma6/pohnpei_ascii/Glochidion_ramiflorum_ascii.txt /gpfs_home/vsharma6/data/vsharma6/pohnpei_out/Glochidion_ramiflorum_out.txt
./bin/metamap16 -q /gpfs_home/vsharma6/data/vsharma6/pohnpei_ascii/Haplopteris_elongata_ascii.txt /gpfs_home/vsharma6/data/vsharma6/pohnpei_out/Haplopteris_elongata_out.txt
./bin/metamap16 -q /gpfs_home/vsharma6/data/vsharma6/pohnpei_ascii/Hibiscus_rosa-sinensis_ascii.txt /gpfs_home/vsharma6/data/vsharma6/pohnpei_out/Hibiscus_rosa-sinensis_out.txt
./bin/metamap16 -q /gpfs_home/vsharma6/data/vsharma6/pohnpei_ascii/Hibiscus_tiliaceus_ascii.txt /gpfs_home/vsharma6/data/vsharma6/pohnpei_out/Hibiscus_tiliaceus_out.txt
./bin/metamap16 -q /gpfs_home/vsharma6/data/vsharma6/pohnpei_ascii/Histiopteris_incisa_ascii.txt /gpfs_home/vsharma6/data/vsharma6/pohnpei_out/Histiopteris_incisa_out.txt
./bin/metamap16 -q /gpfs_home/vsharma6/data/vsharma6/pohnpei_ascii/Huperzia_phlegmaria_ascii.txt /gpfs_home/vsharma6/data/vsharma6/pohnpei_out/Huperzia_phlegmaria_out.txt
./bin/metamap16 -q /gpfs_home/vsharma6/data/vsharma6/pohnpei_ascii/Hymenocallis_littoralis_ascii.txt /gpfs_home/vsharma6/data/vsharma6/pohnpei_out/Hymenocallis_littoralis_out.txt
./bin/metamap16 -q /gpfs_home/vsharma6/data/vsharma6/pohnpei_ascii/Inocarpus_fagifer_ascii.txt /gpfs_home/vsharma6/data/vsharma6/pohnpei_out/Inocarpus_fagifer_out.txt
./bin/metamap16 -q /gpfs_home/vsharma6/data/vsharma6/pohnpei_ascii/Ipomoea_littoralis_ascii.txt /gpfs_home/vsharma6/data/vsharma6/pohnpei_out/Ipomoea_littoralis_out.txt
./bin/metamap16 -q /gpfs_home/vsharma6/data/vsharma6/pohnpei_ascii/Ipomoea_mauritiana_ascii.txt /gpfs_home/vsharma6/data/vsharma6/pohnpei_out/Ipomoea_mauritiana_out.txt
./bin/metamap16 -q /gpfs_home/vsharma6/data/vsharma6/pohnpei_ascii/Ischaemum_polystachyum_ascii.txt /gpfs_home/vsharma6/data/vsharma6/pohnpei_out/Ischaemum_polystachyum_out.txt
./bin/metamap16 -q /gpfs_home/vsharma6/data/vsharma6/pohnpei_ascii/Ixora_casei_ascii.txt /gpfs_home/vsharma6/data/vsharma6/pohnpei_out/Ixora_casei_out.txt
./bin/metamap16 -q /gpfs_home/vsharma6/data/vsharma6/pohnpei_ascii/Kyllinga_brevifolia_ascii.txt /gpfs_home/vsharma6/data/vsharma6/pohnpei_out/Kyllinga_brevifolia_out.txt
./bin/metamap16 -q /gpfs_home/vsharma6/data/vsharma6/pohnpei_ascii/Luffa_cylindrica_ascii.txt /gpfs_home/vsharma6/data/vsharma6/pohnpei_out/Luffa_cylindrica_out.txt
./bin/metamap16 -q /gpfs_home/vsharma6/data/vsharma6/pohnpei_ascii/Lumnitzera_littorea_ascii.txt /gpfs_home/vsharma6/data/vsharma6/pohnpei_out/Lumnitzera_littorea_out.txt
./bin/metamap16 -q /gpfs_home/vsharma6/data/vsharma6/pohnpei_ascii/Macaranga_carolinensis_ascii.txt /gpfs_home/vsharma6/data/vsharma6/pohnpei_out/Macaranga_carolinensis_out.txt
./bin/metamap16 -q /gpfs_home/vsharma6/data/vsharma6/pohnpei_ascii/Mangigera_indica_ascii.txt /gpfs_home/vsharma6/data/vsharma6/pohnpei_out/Mangigera_indica_out.txt
./bin/metamap16 -q /gpfs_home/vsharma6/data/vsharma6/pohnpei_ascii/Melanthera_biflora_ascii.txt /gpfs_home/vsharma6/data/vsharma6/pohnpei_out/Melanthera_biflora_out.txt
./bin/metamap16 -q /gpfs_home/vsharma6/data/vsharma6/pohnpei_ascii/Merremia_peltata_ascii.txt /gpfs_home/vsharma6/data/vsharma6/pohnpei_out/Merremia_peltata_out.txt
./bin/metamap16 -q /gpfs_home/vsharma6/data/vsharma6/pohnpei_ascii/Metroxylon_amicarum_ascii.txt /gpfs_home/vsharma6/data/vsharma6/pohnpei_out/Metroxylon_amicarum_out.txt
./bin/metamap16 -q /gpfs_home/vsharma6/data/vsharma6/pohnpei_ascii/Morinda_citrifolia_ascii.txt /gpfs_home/vsharma6/data/vsharma6/pohnpei_out/Morinda_citrifolia_out.txt
./bin/metamap16 -q /gpfs_home/vsharma6/data/vsharma6/pohnpei_ascii/Musa_paradisiaca_ascii.txt /gpfs_home/vsharma6/data/vsharma6/pohnpei_out/Musa_paradisiaca_out.txt
./bin/metamap16 -q /gpfs_home/vsharma6/data/vsharma6/pohnpei_ascii/Myristica_hypargyraea_ascii.txt /gpfs_home/vsharma6/data/vsharma6/pohnpei_out/Myristica_hypargyraea_out.txt
./bin/metamap16 -q /gpfs_home/vsharma6/data/vsharma6/pohnpei_ascii/Nephrolepis_obliterata_ascii.txt /gpfs_home/vsharma6/data/vsharma6/pohnpei_out/Nephrolepis_obliterata_out.txt
./bin/metamap16 -q /gpfs_home/vsharma6/data/vsharma6/pohnpei_ascii/Nicotiana_tabacum_ascii.txt /gpfs_home/vsharma6/data/vsharma6/pohnpei_out/Nicotiana_tabacum_out.txt
./bin/metamap16 -q /gpfs_home/vsharma6/data/vsharma6/pohnpei_ascii/Pandanus_textorius_ascii.txt /gpfs_home/vsharma6/data/vsharma6/pohnpei_out/Pandanus_textorius_out.txt
./bin/metamap16 -q /gpfs_home/vsharma6/data/vsharma6/pohnpei_ascii/Paraderris_elliptica_ascii.txt /gpfs_home/vsharma6/data/vsharma6/pohnpei_out/Paraderris_elliptica_out.txt
./bin/metamap16 -q /gpfs_home/vsharma6/data/vsharma6/pohnpei_ascii/Paspalum_vaginatum_ascii.txt /gpfs_home/vsharma6/data/vsharma6/pohnpei_out/Paspalum_vaginatum_out.txt
./bin/metamap16 -q /gpfs_home/vsharma6/data/vsharma6/pohnpei_ascii/Passiflora_foetida_ascii.txt /gpfs_home/vsharma6/data/vsharma6/pohnpei_out/Passiflora_foetida_out.txt
./bin/metamap16 -q /gpfs_home/vsharma6/data/vsharma6/pohnpei_ascii/Phragmites_karka_ascii.txt /gpfs_home/vsharma6/data/vsharma6/pohnpei_out/Phragmites_karka_out.txt
./bin/metamap16 -q /gpfs_home/vsharma6/data/vsharma6/pohnpei_ascii/Phyllanthus_amarus_ascii.txt /gpfs_home/vsharma6/data/vsharma6/pohnpei_out/Phyllanthus_amarus_out.txt
./bin/metamap16 -q /gpfs_home/vsharma6/data/vsharma6/pohnpei_ascii/Piper_methysticum_ascii.txt /gpfs_home/vsharma6/data/vsharma6/pohnpei_out/Piper_methysticum_out.txt
./bin/metamap16 -q /gpfs_home/vsharma6/data/vsharma6/pohnpei_ascii/Piper_ponapense_ascii.txt /gpfs_home/vsharma6/data/vsharma6/pohnpei_out/Piper_ponapense_out.txt
./bin/metamap16 -q /gpfs_home/vsharma6/data/vsharma6/pohnpei_ascii/Premna_serratifolia_ascii.txt /gpfs_home/vsharma6/data/vsharma6/pohnpei_out/Premna_serratifolia_out.txt
./bin/metamap16 -q /gpfs_home/vsharma6/data/vsharma6/pohnpei_ascii/Procris_pedunculata_ascii.txt /gpfs_home/vsharma6/data/vsharma6/pohnpei_out/Procris_pedunculata_out.txt
./bin/metamap16 -q /gpfs_home/vsharma6/data/vsharma6/pohnpei_ascii/Psidium_guajava_ascii.txt /gpfs_home/vsharma6/data/vsharma6/pohnpei_out/Psidium_guajava_out.txt
./bin/metamap16 -q /gpfs_home/vsharma6/data/vsharma6/pohnpei_ascii/Rhizophora_apiculata_ascii.txt /gpfs_home/vsharma6/data/vsharma6/pohnpei_out/Rhizophora_apiculata_out.txt
./bin/metamap16 -q /gpfs_home/vsharma6/data/vsharma6/pohnpei_ascii/Rhizophora_mucronata_ascii.txt /gpfs_home/vsharma6/data/vsharma6/pohnpei_out/Rhizophora_mucronata_out.txt
./bin/metamap16 -q /gpfs_home/vsharma6/data/vsharma6/pohnpei_ascii/Saccharum_spontaneum_ascii.txt /gpfs_home/vsharma6/data/vsharma6/pohnpei_out/Saccharum_spontaneum_out.txt
./bin/metamap16 -q /gpfs_home/vsharma6/data/vsharma6/pohnpei_ascii/Senna_alata_ascii.txt /gpfs_home/vsharma6/data/vsharma6/pohnpei_out/Senna_alata_out.txt
./bin/metamap16 -q /gpfs_home/vsharma6/data/vsharma6/pohnpei_ascii/Solenostemon_scutellarioides_ascii.txt /gpfs_home/vsharma6/data/vsharma6/pohnpei_out/Solenostemon_scutellarioides_out.txt
./bin/metamap16 -q /gpfs_home/vsharma6/data/vsharma6/pohnpei_ascii/Sonneratia_alba_ascii.txt /gpfs_home/vsharma6/data/vsharma6/pohnpei_out/Sonneratia_alba_out.txt
./bin/metamap16 -q /gpfs_home/vsharma6/data/vsharma6/pohnpei_ascii/Sphaeropteris_nigricans_ascii.txt /gpfs_home/vsharma6/data/vsharma6/pohnpei_out/Sphaeropteris_nigricans_out.txt
./bin/metamap16 -q /gpfs_home/vsharma6/data/vsharma6/pohnpei_ascii/Tacca_leontopetaloides_ascii.txt /gpfs_home/vsharma6/data/vsharma6/pohnpei_out/Tacca_leontopetaloides_out.txt
./bin/metamap16 -q /gpfs_home/vsharma6/data/vsharma6/pohnpei_ascii/Terminalia_catappa_ascii.txt /gpfs_home/vsharma6/data/vsharma6/pohnpei_out/Terminalia_catappa_out.txt
./bin/metamap16 -q /gpfs_home/vsharma6/data/vsharma6/pohnpei_ascii/Urena_lobata_ascii.txt /gpfs_home/vsharma6/data/vsharma6/pohnpei_out/Urena_lobata_out.txt
./bin/metamap16 -q /gpfs_home/vsharma6/data/vsharma6/pohnpei_ascii/Vigna_marina_ascii.txt /gpfs_home/vsharma6/data/vsharma6/pohnpei_out/Vigna_marina_out.txt
./bin/metamap16 -q /gpfs_home/vsharma6/data/vsharma6/pohnpei_ascii/Zingiber_zerumbet_ascii.txt /gpfs_home/vsharma6/data/vsharma6/pohnpei_out/Zingiber_zerumbet_out.txt
